spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sahil-Naik7602/config-server-BlogConnect
          default-label: main
server:
  port: 8000
